name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REGISTRY : ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}           # set this to your Amazon ECR repository name
                                               # file, e.g. .aws/task-definition.json

jobs:
  django:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir Django
        pip install ruff
    - name: Lint with ruff
      run: |
        ruff check
    - name: Run Tests
      run: |
        python manage.py test

  docker:
    name: Docker Build & Push ECR
    runs-on: ubuntu-latest
    needs: django

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      # Login
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-1 \
          | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com

      # Build image
      - name: Build Docker image
        run: |
          docker build -t django-polls .

      # Tag image
      - name: Tag Docker image for ECR
        run: |
          docker tag django-polls:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/django-polls:latest

      # Push image
      - name: Push Docker image to ECR
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/django-polls:latest